# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Colin P. Stark
tagline:             'Geophysicist'
description:         'Colin P. Starks''s Homepage'
url:                 http://cstarknyc.github.io/tmp
baseurl:             'http://cstarknyc.github.io/tmp'
paginate:            8

# About/contact
author:
  name:             Colin P. Stark
  url:              http://cstarknyc.github.io
  email:            cstarknyc@gmail.com
