# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Progressive Hypsometry
tagline:             'and the glacial limitation of tropical mountain ranges'
description:         'Progressive Hypsometry'
url:                 '/tmp'
baseurl:             '/tmp'
paginate:            8

# About/contact
author:
  name:             CPS
  url:              https://github.com/cstarknyc
  email:            cstarknyc@gmail.com
